name: Automated static testing

on: push
jobs:
  njsscan:
      runs-on: ubuntu-latest
      name: njsscan check
      steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'

  Scan-Build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/db
        key: ${{ runner.os }}-${{ hashFiles('requirements*.txt') }}
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        VDB_HOME: ${{ github.workspace }}/db
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        output: reports
    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm test