
on:
  push:
  pull_request:
  schedule:
    - cron: '*/15 * * * *'

name: Find Secrets
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: max/secret-scan@master
      with:
          exclude_path: 'package.json'
          exclude_path: 'package-lock.json'
